using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Namespace;

namespace Namespace.Tests
{
    [TestClass]
    public class Class1Tests
    {
        [TestMethod]
        public void MainTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Method1Test()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Method2Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}