using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Namespace.Class2;

namespace Namespace.Class2.Tests
{
    [TestClass]
    public class TestClass1Tests
    {
        [TestMethod]
        public void Method1Test()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Method1Test()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Method2Test()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Method3Test()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Method4Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Namespace.Class3;

namespace Namespace.Class3.Tests
{
    [TestClass]
    public class Class3Tests
    {
        [TestMethod]
        public void Method1Test()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Method2Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}